Better usage of image layer caching

diff --git a/build/docker/nginx/Dockerfile b/build/docker/nginx/Dockerfile
--- a/build/docker/nginx/Dockerfile
+++ b/build/docker/nginx/Dockerfile
@@ -6,8 +6,6 @@ ENV \
     LANG="C.UTF-8" \
     LC_ALL="C.UTF-8"
 
-COPY assets/ /
-
 RUN set -ex && \
     \
     # Install base packages
@@ -16,13 +14,17 @@ RUN set -ex && \
     apt-get install --yes --no-install-recommends \
         ca-certificates && \
     \
+    # Clean up
+    rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/* /var/cache/apt/*
+
+COPY assets/ /
+
+RUN set -ex && \
+    \
     # Trust certificate
     chmod 400 /certificate/* && \
     cp /certificate/*.crt /usr/local/share/ca-certificates && \
-    update-ca-certificates && \
-    \
-    # Clean up
-    rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/* /var/cache/apt/*
+    update-ca-certificates
 
 WORKDIR /application
 EXPOSE 8080 8443
diff --git a/build/docker/postgres/Dockerfile b/build/docker/postgres/Dockerfile
--- a/build/docker/postgres/Dockerfile
+++ b/build/docker/postgres/Dockerfile
@@ -6,22 +6,24 @@ ENV \
     LANG="C.UTF-8" \
     LC_ALL="C.UTF-8"
 
-COPY assets/ /
-
 RUN set -ex && \
     \
     # Install base packages
     apt-get update --yes && \
     apt-get upgrade --yes && \
     \
+    # Clean up
+    rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/* /var/cache/apt/*
+
+COPY assets/ /
+
+RUN set -ex && \
+    \
     # Set file permissions
     chmod 0600 /etc/postgresql/certificate.* && \
     chown -R postgres:postgres /etc/postgresql && \
     find /sql -type d -exec chmod 777 {} \; && \
-    find /sql -type f -exec chmod 666 {} \; && \
-    \
-    # Clean up
-    rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/* /var/cache/apt/*
+    find /sql -type f -exec chmod 666 {} \;
 
 WORKDIR /sql
 EXPOSE 5432
